<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="identifier"
    nsURI="http://sdq.ipd.uka.de/Identifier/1.0" nsPrefix="identifier">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;p>&#xD;&#xA;    Provides a package for uniquely identifiable elements&#xD;&#xA;&lt;/p>"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xD;&#xA;    Inherit from this entity to make an element uniquely identifiable.&lt;br />&#xD;&#xA;    Identifiers&amp;nbsp;are&amp;nbsp;not&amp;nbsp;fixed&amp;nbsp;to&amp;nbsp;one&amp;nbsp;realization.&lt;br />&#xD;&#xA;    GUIDs&amp;nbsp;are&amp;nbsp;recommend.&amp;nbsp;GUIDs&amp;nbsp;are&amp;nbsp;described&amp;nbsp;in&amp;nbsp;their&amp;nbsp;own&amp;nbsp;model.&amp;nbsp;See&amp;nbsp;GUIDModel&amp;nbsp;(GUID.emx).&lt;br />&#xD;&#xA;    Identifier&amp;nbsp;implementations&amp;nbsp;can&amp;nbsp;be&amp;nbsp;found&amp;nbsp;in&amp;nbsp;external&amp;nbsp;projects&amp;nbsp;only.&#xD;&#xA;&lt;/p>"/>
    </eAnnotations>
    <eOperations name="idHasToBeUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="--self.allInstances()->isUnique(p | p.id)&#xD;&#xA;Identifier.allInstances()->isUnique(p: Identifier | p.id)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifier attribute, in the default PCM implementation, this field is filled with a randomly generated UUID value"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="id"/>
        <details key="namespace" value="http://sdq.ipd.uka.de/Identifier/1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
