/*
 * generated by Xtext
 */
package kieker.tools.rl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RecordLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/cau/cs/se/instrumentation/rl/parser/antlr/internal/InternalRecordLang.tokens");
	}
}
