/**
 * generated by Xtext
 */
package de.cau.cs.se.instrumentation.rl.ui.labeling;

import com.google.inject.Inject;
import de.cau.cs.se.instrumentation.rl.recordLang.Classifier;
import de.cau.cs.se.instrumentation.rl.recordLang.IntLiteral;
import de.cau.cs.se.instrumentation.rl.recordLang.Property;
import de.cau.cs.se.instrumentation.rl.recordLang.StringLiteral;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class RecordLangLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public RecordLangLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Property e) {
    Classifier _type = e.getType();
    EClassifier _class_ = _type.getClass_();
    String _name = _class_.getName();
    String _plus = (_name + " ");
    String _name_1 = e.getName();
    String _plus_1 = (_plus + _name_1);
    return _plus_1;
  }
  
  public String text(final StringLiteral e) {
    String _value = e.getValue();
    String _plus = ("\'" + _value);
    String _plus_1 = (_plus + "\'");
    return _plus_1;
  }
  
  public int text(final IntLiteral e) {
    int _value = e.getValue();
    return _value;
  }
}
