/**
 * generated by Xtext
 */
package de.cau.cs.se.instrumentation.al.validation;

import de.cau.cs.se.instrumentation.al.validation.AbstractApplicationLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ApplicationLangValidator extends AbstractApplicationLangValidator {
}
