<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="probfunction"
    nsURI="http://sdq.ipd.uka.de/ProbFunction/1.0" nsPrefix="probfunction">
  <eClassifiers xsi:type="ecore:EClass" name="BoxedPDF" eSuperTypes="#//ProbabilityDensityFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="samples" ordered="false"
        upperBound="-1" eType="#//ContinuousSample" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilityDensityFunction" abstract="true"
      eSuperTypes="#//ProbabilityFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilityFunction" abstract="true"
      eSuperTypes="../../de.uka.ipd.sdq.units/model/Units.ecore#//UnitCarryingElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousSample">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilityMassFunction" eSuperTypes="#//ProbabilityFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="samples" upperBound="-1"
        eType="#//Sample" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderedDomain" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sample">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        unique="false" lowerBound="1">
      <eGenericType eTypeParameter="#//Sample/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SamplePDF" eSuperTypes="#//ProbabilityDensityFunction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false"
        upperBound="-1" eType="#//Complex" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Complex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="real" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imaginary" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousPDF" abstract="true" eSuperTypes="#//ProbabilityDensityFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExponentialDistribution" eSuperTypes="#//ContinuousPDF">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalDistribution" eSuperTypes="#//ContinuousPDF">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mu" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigma" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LognormalDistribution" eSuperTypes="#//ContinuousPDF">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Lognormal distribution with parameters scale parameter mu and shape parameter sigma > 0. See  {@link umontreal.iro.lecuyer.probdist.LognormalDist} for definition."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mu" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="scale parameter mu (see {@link umontreal.iro.lecuyer.probdist.LognormalDist}.)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigma" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="shape parameter sigma (see {@link umontreal.iro.lecuyer.probdist.LognormalDist}.)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GammaDistribution" eSuperTypes="#//ContinuousPDF">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Gamma distribution with shape parameter alpha > 0 (also called k in Wikipedia) and scale parameter theta > 0 (called lambda in umontreal.iro.lecuyer.probdist.GammaDist). The scale parameter theta is the inverse of the rate beta which is also sometimes given to characterise a Gamma distribution. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Shape parameter"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theta" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Scale parameter, which is the inverse of the rate parameter beta which is also sometimes given to characterise a Gamma distribution. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
