<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stoex"
    nsURI="http://sdq.ipd.uka.de/StochasticExpressions/1.0" nsPrefix="stoex">
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//AbstractNamedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceReference" eSuperTypes="#//AbstractNamedReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerReference_NamespaceReference"
        ordered="false" lowerBound="1" eType="#//AbstractNamedReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TermOperations">
    <eLiterals name="ADD"/>
    <eLiterals name="SUB" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProductOperations">
    <eLiterals name="MULT"/>
    <eLiterals name="DIV" value="1"/>
    <eLiterals name="MOD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompareOperations">
    <eLiterals name="GREATER"/>
    <eLiterals name="EQUALS" value="1"/>
    <eLiterals name="LESS" value="2"/>
    <eLiterals name="NOTEQUAL" value="3"/>
    <eLiterals name="LESSEQUAL" value="4"/>
    <eLiterals name="GREATEREQUAL" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id_Variable" ordered="false"
        lowerBound="1" eType="#//AbstractNamedReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" abstract="true" eSuperTypes="#//Unary"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unary" abstract="true" eSuperTypes="#//Power"/>
  <eClassifiers xsi:type="ecore:EClass" name="Power" abstract="true" eSuperTypes="#//Product"/>
  <eClassifiers xsi:type="ecore:EClass" name="Product" abstract="true" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" eSuperTypes="#//Comparison"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" abstract="true" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true" eSuperTypes="#//IfElse"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfElse" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermExpression" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false" lowerBound="1"
        eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false"
        lowerBound="1" eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" ordered="false"
        lowerBound="1" eType="#//TermOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductExpression" eSuperTypes="#//Product">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false" lowerBound="1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false"
        lowerBound="1" eType="#//Power" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" ordered="false"
        lowerBound="1" eType="#//ProductOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilityFunctionLiteral" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function_ProbabilityFunctionLiteral"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.probfunction/model/ProbabilityFunction.ecore#//ProbabilityFunction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthesis" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerExpression" ordered="false"
        lowerBound="1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericLiteral" abstract="true" eSuperTypes="../../de.uka.ipd.sdq.units/model/Units.ecore#//UnitCarryingElement #//Atom"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="#//NumericLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleLiteral" eSuperTypes="#//NumericLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareExpression" eSuperTypes="#//Comparison">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false" lowerBound="1"
        eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false"
        lowerBound="1" eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" ordered="false"
        lowerBound="1" eType="#//CompareOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLiteral" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerExpression" eSuperTypes="#//Power">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1"
        eType="#//Power" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exponent" ordered="false"
        lowerBound="1" eType="#//Unary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperatorExpression" eSuperTypes="#//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false"
        lowerBound="1" eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" ordered="false"
        lowerBound="1" eType="#//BooleanOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperations">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="XOR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//Unary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" ordered="false"
        lowerBound="1" eType="#//Unary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeExpression" eSuperTypes="#//Unary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" ordered="false"
        lowerBound="1" eType="#//Unary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionLiteral" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters_FunctionLiteral"
        ordered="false" upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfElseExpression" eSuperTypes="#//IfElse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifExpression" ordered="false"
        lowerBound="1" eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" ordered="false"
        lowerBound="1" eType="#//BooleanExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionExpression" ordered="false"
        lowerBound="1" eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//Expression" changeable="false" volatile="true" transient="true"
        unsettable="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=""/>
        <details key="namespace" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
