/*
 * generated by Xtext
 */
package kieker.develop.al.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAspectLangValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(kieker.develop.al.aspectLang.AspectLangPackage.eINSTANCE);
		return result;
	}
}
