/**
 *
 * $Id$
 */
package de.cau.cs.se.instrumantation.model.structure.validation;

import org.eclipse.emf.common.util.EList;

import de.cau.cs.se.instrumantation.model.structure.Attribute;
import de.cau.cs.se.instrumantation.model.structure.ContainerModifier;
import de.cau.cs.se.instrumantation.model.structure.Operation;
import de.cau.cs.se.instrumantation.model.structure.TypeReference;

/**
 * A sample validator interface for {@link de.cau.cs.se.instrumantation.model.structure.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateModifier(ContainerModifier value);

	boolean validateOperations(EList<Operation> value);

	boolean validateAttributes(EList<Attribute> value);

	boolean validateType(TypeReference value);
}
