/*
* generated by Xtext
*/
package de.cau.cs.se.instrumentation.language.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class InstrumentationLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
