/*
 * generated by Xtext
 */
package de.cau.cs.se.instrumentation.al.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.se.instrumentation.al.ui.internal.ApplicationLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ApplicationLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ApplicationLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ApplicationLangActivator.getInstance().getInjector(ApplicationLangActivator.DE_CAU_CS_SE_INSTRUMENTATION_AL_APPLICATIONLANG);
	}
	
}
