/*
* generated by Xtext
*/
package de.cau.cs.se.instrumentation.rl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RecordLangStandaloneSetup extends RecordLangStandaloneSetupGenerated{

	public static void doSetup() {
		new RecordLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

