/*
* generated by Xtext
*/
package de.cau.cs.se.instrumentation.rl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RecordLangGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPackagesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPackagesPackageParserRuleCall_2_0 = (RuleCall)cPackagesAssignment_2.eContents().get(0);
		private final Assignment cImportsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImportsImportParserRuleCall_3_0 = (RuleCall)cImportsAssignment_3.eContents().get(0);
		private final Assignment cTypesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypesTypeParserRuleCall_4_0 = (RuleCall)cTypesAssignment_4.eContents().get(0);
		
		//Model:
		//	"package" name=QualifiedName packages+=Package* imports+=Import* types+=Type*;
		public ParserRule getRule() { return rule; }

		//"package" name=QualifiedName packages+=Package* imports+=Import* types+=Type*
		public Group getGroup() { return cGroup; }

		//"package"
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//packages+=Package*
		public Assignment getPackagesAssignment_2() { return cPackagesAssignment_2; }

		//Package
		public RuleCall getPackagesPackageParserRuleCall_2_0() { return cPackagesPackageParserRuleCall_2_0; }

		//imports+=Import*
		public Assignment getImportsAssignment_3() { return cImportsAssignment_3; }

		//Import
		public RuleCall getImportsImportParserRuleCall_3_0() { return cImportsImportParserRuleCall_3_0; }

		//types+=Type*
		public Assignment getTypesAssignment_4() { return cTypesAssignment_4; }

		//Type
		public RuleCall getTypesTypeParserRuleCall_4_0() { return cTypesTypeParserRuleCall_4_0; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//	"import" importedNamespace=QualifiedNameWithWildcard;
		public ParserRule getRule() { return rule; }

		//"import" importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}

	public class PackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Package");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPackageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cPackageEPackageCrossReference_2_0 = (CrossReference)cPackageAssignment_2.eContents().get(0);
		private final RuleCall cPackageEPackageSTRINGTerminalRuleCall_2_0_1 = (RuleCall)cPackageEPackageCrossReference_2_0.eContents().get(1);
		
		//Package:
		//	"use" name=ID package=[ecore::EPackage|STRING];
		public ParserRule getRule() { return rule; }

		//"use" name=ID package=[ecore::EPackage|STRING]
		public Group getGroup() { return cGroup; }

		//"use"
		public Keyword getUseKeyword_0() { return cUseKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//package=[ecore::EPackage|STRING]
		public Assignment getPackageAssignment_2() { return cPackageAssignment_2; }

		//[ecore::EPackage|STRING]
		public CrossReference getPackageEPackageCrossReference_2_0() { return cPackageEPackageCrossReference_2_0; }

		//STRING
		public RuleCall getPackageEPackageSTRINGTerminalRuleCall_2_0_1() { return cPackageEPackageSTRINGTerminalRuleCall_2_0_1; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRecordTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTemplateTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//	RecordType | TemplateType;
		public ParserRule getRule() { return rule; }

		//RecordType | TemplateType
		public Alternatives getAlternatives() { return cAlternatives; }

		//RecordType
		public RuleCall getRecordTypeParserRuleCall_0() { return cRecordTypeParserRuleCall_0; }

		//TemplateType
		public RuleCall getTemplateTypeParserRuleCall_1() { return cTemplateTypeParserRuleCall_1; }
	}

	public class TemplateTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TemplateType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cAuthorKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cAuthorAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cAuthorSTRINGTerminalRuleCall_0_1_0 = (RuleCall)cAuthorAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSinceKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cSinceAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cSinceSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cSinceAssignment_1_1.eContents().get(0);
		private final Keyword cTemplateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cParentsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cParentsTemplateTypeCrossReference_4_1_0 = (CrossReference)cParentsAssignment_4_1.eContents().get(0);
		private final RuleCall cParentsTemplateTypeQualifiedNameParserRuleCall_4_1_0_1 = (RuleCall)cParentsTemplateTypeCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cParentsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cParentsTemplateTypeCrossReference_4_2_1_0 = (CrossReference)cParentsAssignment_4_2_1.eContents().get(0);
		private final RuleCall cParentsTemplateTypeQualifiedNameParserRuleCall_4_2_1_0_1 = (RuleCall)cParentsTemplateTypeCrossReference_4_2_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Alternatives cAlternatives_5_1 = (Alternatives)cGroup_5.eContents().get(1);
		private final Assignment cPropertiesAssignment_5_1_0 = (Assignment)cAlternatives_5_1.eContents().get(0);
		private final RuleCall cPropertiesPropertyParserRuleCall_5_1_0_0 = (RuleCall)cPropertiesAssignment_5_1_0.eContents().get(0);
		private final Assignment cConstantsAssignment_5_1_1 = (Assignment)cAlternatives_5_1.eContents().get(1);
		private final RuleCall cConstantsConstantParserRuleCall_5_1_1_0 = (RuleCall)cConstantsAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		
		//TemplateType:
		//	("@author" author=STRING)? ("@since" since=STRING)? "template" name=ID (":" parents+=[TemplateType|QualifiedName] (","
		//	parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?;
		public ParserRule getRule() { return rule; }

		//("@author" author=STRING)? ("@since" since=STRING)? "template" name=ID (":" parents+=[TemplateType|QualifiedName] (","
		//parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?
		public Group getGroup() { return cGroup; }

		//("@author" author=STRING)?
		public Group getGroup_0() { return cGroup_0; }

		//"@author"
		public Keyword getAuthorKeyword_0_0() { return cAuthorKeyword_0_0; }

		//author=STRING
		public Assignment getAuthorAssignment_0_1() { return cAuthorAssignment_0_1; }

		//STRING
		public RuleCall getAuthorSTRINGTerminalRuleCall_0_1_0() { return cAuthorSTRINGTerminalRuleCall_0_1_0; }

		//("@since" since=STRING)?
		public Group getGroup_1() { return cGroup_1; }

		//"@since"
		public Keyword getSinceKeyword_1_0() { return cSinceKeyword_1_0; }

		//since=STRING
		public Assignment getSinceAssignment_1_1() { return cSinceAssignment_1_1; }

		//STRING
		public RuleCall getSinceSTRINGTerminalRuleCall_1_1_0() { return cSinceSTRINGTerminalRuleCall_1_1_0; }

		//"template"
		public Keyword getTemplateKeyword_2() { return cTemplateKeyword_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//(":" parents+=[TemplateType|QualifiedName] ("," parents+=[TemplateType|QualifiedName])*)?
		public Group getGroup_4() { return cGroup_4; }

		//":"
		public Keyword getColonKeyword_4_0() { return cColonKeyword_4_0; }

		//parents+=[TemplateType|QualifiedName]
		public Assignment getParentsAssignment_4_1() { return cParentsAssignment_4_1; }

		//[TemplateType|QualifiedName]
		public CrossReference getParentsTemplateTypeCrossReference_4_1_0() { return cParentsTemplateTypeCrossReference_4_1_0; }

		//QualifiedName
		public RuleCall getParentsTemplateTypeQualifiedNameParserRuleCall_4_1_0_1() { return cParentsTemplateTypeQualifiedNameParserRuleCall_4_1_0_1; }

		//("," parents+=[TemplateType|QualifiedName])*
		public Group getGroup_4_2() { return cGroup_4_2; }

		//","
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }

		//parents+=[TemplateType|QualifiedName]
		public Assignment getParentsAssignment_4_2_1() { return cParentsAssignment_4_2_1; }

		//[TemplateType|QualifiedName]
		public CrossReference getParentsTemplateTypeCrossReference_4_2_1_0() { return cParentsTemplateTypeCrossReference_4_2_1_0; }

		//QualifiedName
		public RuleCall getParentsTemplateTypeQualifiedNameParserRuleCall_4_2_1_0_1() { return cParentsTemplateTypeQualifiedNameParserRuleCall_4_2_1_0_1; }

		//("{" (properties+=Property | constants+=Constant)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_0() { return cLeftCurlyBracketKeyword_5_0; }

		//(properties+=Property | constants+=Constant)*
		public Alternatives getAlternatives_5_1() { return cAlternatives_5_1; }

		//properties+=Property
		public Assignment getPropertiesAssignment_5_1_0() { return cPropertiesAssignment_5_1_0; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_5_1_0_0() { return cPropertiesPropertyParserRuleCall_5_1_0_0; }

		//constants+=Constant
		public Assignment getConstantsAssignment_5_1_1() { return cConstantsAssignment_5_1_1; }

		//Constant
		public RuleCall getConstantsConstantParserRuleCall_5_1_1_0() { return cConstantsConstantParserRuleCall_5_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_2() { return cRightCurlyBracketKeyword_5_2; }
	}

	public class RecordTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RecordType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cAuthorKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cAuthorAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cAuthorSTRINGTerminalRuleCall_0_1_0 = (RuleCall)cAuthorAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSinceKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cSinceAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cSinceSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cSinceAssignment_1_1.eContents().get(0);
		private final Assignment cAbstractAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cAbstractAbstractKeyword_2_0 = (Keyword)cAbstractAssignment_2.eContents().get(0);
		private final Keyword cEntityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExtendsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cParentAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cParentRecordTypeCrossReference_5_1_0 = (CrossReference)cParentAssignment_5_1.eContents().get(0);
		private final RuleCall cParentRecordTypeQualifiedNameParserRuleCall_5_1_0_1 = (RuleCall)cParentRecordTypeCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cParentsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cParentsTemplateTypeCrossReference_6_1_0 = (CrossReference)cParentsAssignment_6_1.eContents().get(0);
		private final RuleCall cParentsTemplateTypeQualifiedNameParserRuleCall_6_1_0_1 = (RuleCall)cParentsTemplateTypeCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cCommaKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cParentsAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final CrossReference cParentsTemplateTypeCrossReference_6_2_1_0 = (CrossReference)cParentsAssignment_6_2_1.eContents().get(0);
		private final RuleCall cParentsTemplateTypeQualifiedNameParserRuleCall_6_2_1_0_1 = (RuleCall)cParentsTemplateTypeCrossReference_6_2_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Alternatives cAlternatives_7_1 = (Alternatives)cGroup_7.eContents().get(1);
		private final Assignment cPropertiesAssignment_7_1_0 = (Assignment)cAlternatives_7_1.eContents().get(0);
		private final RuleCall cPropertiesPropertyParserRuleCall_7_1_0_0 = (RuleCall)cPropertiesAssignment_7_1_0.eContents().get(0);
		private final Assignment cConstantsAssignment_7_1_1 = (Assignment)cAlternatives_7_1.eContents().get(1);
		private final RuleCall cConstantsConstantParserRuleCall_7_1_1_0 = (RuleCall)cConstantsAssignment_7_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		
		//RecordType:
		//	("@author" author=STRING)? ("@since" since=STRING)? abstract?="abstract"? "entity" name=ID ("extends"
		//	parent=[RecordType|QualifiedName])? (":" parents+=[TemplateType|QualifiedName] (","
		//	parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?;
		public ParserRule getRule() { return rule; }

		//("@author" author=STRING)? ("@since" since=STRING)? abstract?="abstract"? "entity" name=ID ("extends"
		//parent=[RecordType|QualifiedName])? (":" parents+=[TemplateType|QualifiedName] (","
		//parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?
		public Group getGroup() { return cGroup; }

		//("@author" author=STRING)?
		public Group getGroup_0() { return cGroup_0; }

		//"@author"
		public Keyword getAuthorKeyword_0_0() { return cAuthorKeyword_0_0; }

		//author=STRING
		public Assignment getAuthorAssignment_0_1() { return cAuthorAssignment_0_1; }

		//STRING
		public RuleCall getAuthorSTRINGTerminalRuleCall_0_1_0() { return cAuthorSTRINGTerminalRuleCall_0_1_0; }

		//("@since" since=STRING)?
		public Group getGroup_1() { return cGroup_1; }

		//"@since"
		public Keyword getSinceKeyword_1_0() { return cSinceKeyword_1_0; }

		//since=STRING
		public Assignment getSinceAssignment_1_1() { return cSinceAssignment_1_1; }

		//STRING
		public RuleCall getSinceSTRINGTerminalRuleCall_1_1_0() { return cSinceSTRINGTerminalRuleCall_1_1_0; }

		//abstract?="abstract"?
		public Assignment getAbstractAssignment_2() { return cAbstractAssignment_2; }

		//"abstract"
		public Keyword getAbstractAbstractKeyword_2_0() { return cAbstractAbstractKeyword_2_0; }

		//"entity"
		public Keyword getEntityKeyword_3() { return cEntityKeyword_3; }

		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }

		//("extends" parent=[RecordType|QualifiedName])?
		public Group getGroup_5() { return cGroup_5; }

		//"extends"
		public Keyword getExtendsKeyword_5_0() { return cExtendsKeyword_5_0; }

		//parent=[RecordType|QualifiedName]
		public Assignment getParentAssignment_5_1() { return cParentAssignment_5_1; }

		//[RecordType|QualifiedName]
		public CrossReference getParentRecordTypeCrossReference_5_1_0() { return cParentRecordTypeCrossReference_5_1_0; }

		//QualifiedName
		public RuleCall getParentRecordTypeQualifiedNameParserRuleCall_5_1_0_1() { return cParentRecordTypeQualifiedNameParserRuleCall_5_1_0_1; }

		//(":" parents+=[TemplateType|QualifiedName] ("," parents+=[TemplateType|QualifiedName])*)?
		public Group getGroup_6() { return cGroup_6; }

		//":"
		public Keyword getColonKeyword_6_0() { return cColonKeyword_6_0; }

		//parents+=[TemplateType|QualifiedName]
		public Assignment getParentsAssignment_6_1() { return cParentsAssignment_6_1; }

		//[TemplateType|QualifiedName]
		public CrossReference getParentsTemplateTypeCrossReference_6_1_0() { return cParentsTemplateTypeCrossReference_6_1_0; }

		//QualifiedName
		public RuleCall getParentsTemplateTypeQualifiedNameParserRuleCall_6_1_0_1() { return cParentsTemplateTypeQualifiedNameParserRuleCall_6_1_0_1; }

		//("," parents+=[TemplateType|QualifiedName])*
		public Group getGroup_6_2() { return cGroup_6_2; }

		//","
		public Keyword getCommaKeyword_6_2_0() { return cCommaKeyword_6_2_0; }

		//parents+=[TemplateType|QualifiedName]
		public Assignment getParentsAssignment_6_2_1() { return cParentsAssignment_6_2_1; }

		//[TemplateType|QualifiedName]
		public CrossReference getParentsTemplateTypeCrossReference_6_2_1_0() { return cParentsTemplateTypeCrossReference_6_2_1_0; }

		//QualifiedName
		public RuleCall getParentsTemplateTypeQualifiedNameParserRuleCall_6_2_1_0_1() { return cParentsTemplateTypeQualifiedNameParserRuleCall_6_2_1_0_1; }

		//("{" (properties+=Property | constants+=Constant)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_0() { return cLeftCurlyBracketKeyword_7_0; }

		//(properties+=Property | constants+=Constant)*
		public Alternatives getAlternatives_7_1() { return cAlternatives_7_1; }

		//properties+=Property
		public Assignment getPropertiesAssignment_7_1_0() { return cPropertiesAssignment_7_1_0; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_7_1_0_0() { return cPropertiesPropertyParserRuleCall_7_1_0_0; }

		//constants+=Constant
		public Assignment getConstantsAssignment_7_1_1() { return cConstantsAssignment_7_1_1; }

		//Constant
		public RuleCall getConstantsConstantParserRuleCall_7_1_1_0() { return cConstantsConstantParserRuleCall_7_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_2() { return cRightCurlyBracketKeyword_7_2; }
	}

	public class ConstantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConstKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeClassifierParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueLiteralParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//Constant:
		//	"const" type=Classifier name=ID "=" value=Literal;
		public ParserRule getRule() { return rule; }

		//"const" type=Classifier name=ID "=" value=Literal
		public Group getGroup() { return cGroup; }

		//"const"
		public Keyword getConstKeyword_0() { return cConstKeyword_0; }

		//type=Classifier
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//Classifier
		public RuleCall getTypeClassifierParserRuleCall_1_0() { return cTypeClassifierParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//value=Literal
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//Literal
		public RuleCall getValueLiteralParserRuleCall_4_0() { return cValueLiteralParserRuleCall_4_0; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cModifiersAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cModifiersPropertyModifierEnumRuleCall_0_0 = (RuleCall)cModifiersAssignment_0.eContents().get(0);
		private final Assignment cForeignKeyAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cForeignKeyForeignKeyParserRuleCall_1_0 = (RuleCall)cForeignKeyAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cTypeClassifierParserRuleCall_2_0_0 = (RuleCall)cTypeAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cAliasKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cReferToAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final CrossReference cReferToPropertyCrossReference_2_1_1_0 = (CrossReference)cReferToAssignment_2_1_1.eContents().get(0);
		private final RuleCall cReferToPropertyIDTerminalRuleCall_2_1_1_0_1 = (RuleCall)cReferToPropertyCrossReference_2_1_1_0.eContents().get(1);
		private final Keyword cAsKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cPropertiesAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cPropertiesReferencePropertyParserRuleCall_4_0_1_0 = (RuleCall)cPropertiesAssignment_4_0_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_0_2 = (Keyword)cGroup_4_0.eContents().get(2);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final Keyword cEqualsSignKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cValueAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cValueLiteralParserRuleCall_4_1_1_0 = (RuleCall)cValueAssignment_4_1_1.eContents().get(0);
		
		//Property:
		//	modifiers+=PropertyModifier* foreignKey=ForeignKey? (type=Classifier | "alias" referTo=[Property] "as") name=ID ("{"
		//	properties+=ReferenceProperty* "}" | "=" value=Literal)?;
		public ParserRule getRule() { return rule; }

		//modifiers+=PropertyModifier* foreignKey=ForeignKey? (type=Classifier | "alias" referTo=[Property] "as") name=ID ("{"
		//properties+=ReferenceProperty* "}" | "=" value=Literal)?
		public Group getGroup() { return cGroup; }

		//modifiers+=PropertyModifier*
		public Assignment getModifiersAssignment_0() { return cModifiersAssignment_0; }

		//PropertyModifier
		public RuleCall getModifiersPropertyModifierEnumRuleCall_0_0() { return cModifiersPropertyModifierEnumRuleCall_0_0; }

		//foreignKey=ForeignKey?
		public Assignment getForeignKeyAssignment_1() { return cForeignKeyAssignment_1; }

		//ForeignKey
		public RuleCall getForeignKeyForeignKeyParserRuleCall_1_0() { return cForeignKeyForeignKeyParserRuleCall_1_0; }

		//type=Classifier | "alias" referTo=[Property] "as"
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//type=Classifier
		public Assignment getTypeAssignment_2_0() { return cTypeAssignment_2_0; }

		//Classifier
		public RuleCall getTypeClassifierParserRuleCall_2_0_0() { return cTypeClassifierParserRuleCall_2_0_0; }

		//"alias" referTo=[Property] "as"
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"alias"
		public Keyword getAliasKeyword_2_1_0() { return cAliasKeyword_2_1_0; }

		//referTo=[Property]
		public Assignment getReferToAssignment_2_1_1() { return cReferToAssignment_2_1_1; }

		//[Property]
		public CrossReference getReferToPropertyCrossReference_2_1_1_0() { return cReferToPropertyCrossReference_2_1_1_0; }

		//ID
		public RuleCall getReferToPropertyIDTerminalRuleCall_2_1_1_0_1() { return cReferToPropertyIDTerminalRuleCall_2_1_1_0_1; }

		//"as"
		public Keyword getAsKeyword_2_1_2() { return cAsKeyword_2_1_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//("{" properties+=ReferenceProperty* "}" | "=" value=Literal)?
		public Alternatives getAlternatives_4() { return cAlternatives_4; }

		//"{" properties+=ReferenceProperty* "}"
		public Group getGroup_4_0() { return cGroup_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_0_0() { return cLeftCurlyBracketKeyword_4_0_0; }

		//properties+=ReferenceProperty*
		public Assignment getPropertiesAssignment_4_0_1() { return cPropertiesAssignment_4_0_1; }

		//ReferenceProperty
		public RuleCall getPropertiesReferencePropertyParserRuleCall_4_0_1_0() { return cPropertiesReferencePropertyParserRuleCall_4_0_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_0_2() { return cRightCurlyBracketKeyword_4_0_2; }

		//"=" value=Literal
		public Group getGroup_4_1() { return cGroup_4_1; }

		//"="
		public Keyword getEqualsSignKeyword_4_1_0() { return cEqualsSignKeyword_4_1_0; }

		//value=Literal
		public Assignment getValueAssignment_4_1_1() { return cValueAssignment_4_1_1; }

		//Literal
		public RuleCall getValueLiteralParserRuleCall_4_1_1_0() { return cValueLiteralParserRuleCall_4_1_1_0; }
	}

	public class ForeignKeyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ForeignKey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cByKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRecordTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cRecordTypeRecordTypeCrossReference_2_0 = (CrossReference)cRecordTypeAssignment_2.eContents().get(0);
		private final RuleCall cRecordTypeRecordTypeIDTerminalRuleCall_2_0_1 = (RuleCall)cRecordTypeRecordTypeCrossReference_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPropertyRefAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPropertyRefPropertyCrossReference_4_0 = (CrossReference)cPropertyRefAssignment_4.eContents().get(0);
		private final RuleCall cPropertyRefPropertyIDTerminalRuleCall_4_0_1 = (RuleCall)cPropertyRefPropertyCrossReference_4_0.eContents().get(1);
		
		//ForeignKey:
		//	"grouped" "by" recordType=[RecordType] "." propertyRef=[Property];
		public ParserRule getRule() { return rule; }

		//"grouped" "by" recordType=[RecordType] "." propertyRef=[Property]
		public Group getGroup() { return cGroup; }

		//"grouped"
		public Keyword getGroupedKeyword_0() { return cGroupedKeyword_0; }

		//"by"
		public Keyword getByKeyword_1() { return cByKeyword_1; }

		//recordType=[RecordType]
		public Assignment getRecordTypeAssignment_2() { return cRecordTypeAssignment_2; }

		//[RecordType]
		public CrossReference getRecordTypeRecordTypeCrossReference_2_0() { return cRecordTypeRecordTypeCrossReference_2_0; }

		//ID
		public RuleCall getRecordTypeRecordTypeIDTerminalRuleCall_2_0_1() { return cRecordTypeRecordTypeIDTerminalRuleCall_2_0_1; }

		//"."
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }

		//propertyRef=[Property]
		public Assignment getPropertyRefAssignment_4() { return cPropertyRefAssignment_4; }

		//[Property]
		public CrossReference getPropertyRefPropertyCrossReference_4_0() { return cPropertyRefPropertyCrossReference_4_0; }

		//ID
		public RuleCall getPropertyRefPropertyIDTerminalRuleCall_4_0_1() { return cPropertyRefPropertyIDTerminalRuleCall_4_0_1; }
	}

	public class ClassifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Classifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cPackageAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final CrossReference cPackagePackageCrossReference_0_0_0 = (CrossReference)cPackageAssignment_0_0.eContents().get(0);
		private final RuleCall cPackagePackageIDTerminalRuleCall_0_0_0_1 = (RuleCall)cPackagePackageCrossReference_0_0_0.eContents().get(1);
		private final Keyword cFullStopKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cClassAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cClassEClassifierCrossReference_1_0 = (CrossReference)cClassAssignment_1.eContents().get(0);
		private final RuleCall cClassEClassifierIDTerminalRuleCall_1_0_1 = (RuleCall)cClassEClassifierCrossReference_1_0.eContents().get(1);
		private final Assignment cSizesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSizesArraySizeParserRuleCall_2_0 = (RuleCall)cSizesAssignment_2.eContents().get(0);
		
		//Classifier:
		//	(package=[Package] ".")? class=[ecore::EClassifier] sizes+=ArraySize*;
		public ParserRule getRule() { return rule; }

		//(package=[Package] ".")? class=[ecore::EClassifier] sizes+=ArraySize*
		public Group getGroup() { return cGroup; }

		//(package=[Package] ".")?
		public Group getGroup_0() { return cGroup_0; }

		//package=[Package]
		public Assignment getPackageAssignment_0_0() { return cPackageAssignment_0_0; }

		//[Package]
		public CrossReference getPackagePackageCrossReference_0_0_0() { return cPackagePackageCrossReference_0_0_0; }

		//ID
		public RuleCall getPackagePackageIDTerminalRuleCall_0_0_0_1() { return cPackagePackageIDTerminalRuleCall_0_0_0_1; }

		//"."
		public Keyword getFullStopKeyword_0_1() { return cFullStopKeyword_0_1; }

		//class=[ecore::EClassifier]
		public Assignment getClassAssignment_1() { return cClassAssignment_1; }

		//[ecore::EClassifier]
		public CrossReference getClassEClassifierCrossReference_1_0() { return cClassEClassifierCrossReference_1_0; }

		//ID
		public RuleCall getClassEClassifierIDTerminalRuleCall_1_0_1() { return cClassEClassifierIDTerminalRuleCall_1_0_1; }

		//sizes+=ArraySize*
		public Assignment getSizesAssignment_2() { return cSizesAssignment_2; }

		//ArraySize
		public RuleCall getSizesArraySizeParserRuleCall_2_0() { return cSizesArraySizeParserRuleCall_2_0; }
	}

	public class ArraySizeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArraySize");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArraySizeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSizeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSizeINTTerminalRuleCall_2_0 = (RuleCall)cSizeAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ArraySize:
		//	{ArraySize} "[" size=INT? "]";
		public ParserRule getRule() { return rule; }

		//{ArraySize} "[" size=INT? "]"
		public Group getGroup() { return cGroup; }

		//{ArraySize}
		public Action getArraySizeAction_0() { return cArraySizeAction_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//size=INT?
		public Assignment getSizeAssignment_2() { return cSizeAssignment_2; }

		//INT
		public RuleCall getSizeINTTerminalRuleCall_2_0() { return cSizeINTTerminalRuleCall_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class ReferencePropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReferenceProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRefAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRefEStructuralFeatureCrossReference_0_0 = (CrossReference)cRefAssignment_0.eContents().get(0);
		private final RuleCall cRefEStructuralFeatureIDTerminalRuleCall_0_0_1 = (RuleCall)cRefEStructuralFeatureCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPropertiesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPropertiesReferencePropertyParserRuleCall_2_0 = (RuleCall)cPropertiesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ReferenceProperty:
		//	ref=[ecore::EStructuralFeature] "{" properties+=ReferenceProperty* "}";
		public ParserRule getRule() { return rule; }

		//ref=[ecore::EStructuralFeature] "{" properties+=ReferenceProperty* "}"
		public Group getGroup() { return cGroup; }

		//ref=[ecore::EStructuralFeature]
		public Assignment getRefAssignment_0() { return cRefAssignment_0; }

		//[ecore::EStructuralFeature]
		public CrossReference getRefEStructuralFeatureCrossReference_0_0() { return cRefEStructuralFeatureCrossReference_0_0; }

		//ID
		public RuleCall getRefEStructuralFeatureIDTerminalRuleCall_0_0_1() { return cRefEStructuralFeatureIDTerminalRuleCall_0_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//properties+=ReferenceProperty*
		public Assignment getPropertiesAssignment_2() { return cPropertiesAssignment_2; }

		//ReferenceProperty
		public RuleCall getPropertiesReferencePropertyParserRuleCall_2_0() { return cPropertiesReferencePropertyParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFloatLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cConstantLiteralParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cArrayLiteralParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cBuiltInValueLiteralParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Literal:
		//	StringLiteral | IntLiteral | FloatLiteral | BooleanLiteral | ConstantLiteral | ArrayLiteral | BuiltInValueLiteral;
		public ParserRule getRule() { return rule; }

		//StringLiteral | IntLiteral | FloatLiteral | BooleanLiteral | ConstantLiteral | ArrayLiteral | BuiltInValueLiteral
		public Alternatives getAlternatives() { return cAlternatives; }

		//StringLiteral
		public RuleCall getStringLiteralParserRuleCall_0() { return cStringLiteralParserRuleCall_0; }

		//IntLiteral
		public RuleCall getIntLiteralParserRuleCall_1() { return cIntLiteralParserRuleCall_1; }

		//FloatLiteral
		public RuleCall getFloatLiteralParserRuleCall_2() { return cFloatLiteralParserRuleCall_2; }

		//BooleanLiteral
		public RuleCall getBooleanLiteralParserRuleCall_3() { return cBooleanLiteralParserRuleCall_3; }

		//ConstantLiteral
		public RuleCall getConstantLiteralParserRuleCall_4() { return cConstantLiteralParserRuleCall_4; }

		//ArrayLiteral
		public RuleCall getArrayLiteralParserRuleCall_5() { return cArrayLiteralParserRuleCall_5; }

		//BuiltInValueLiteral
		public RuleCall getBuiltInValueLiteralParserRuleCall_6() { return cBuiltInValueLiteralParserRuleCall_6; }
	}

	public class ArrayLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArrayLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLiteralsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLiteralsLiteralParserRuleCall_1_0 = (RuleCall)cLiteralsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLiteralsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLiteralsLiteralParserRuleCall_2_1_0 = (RuleCall)cLiteralsAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ArrayLiteral:
		//	"{" literals+=Literal ("," literals+=Literal)* "}";
		public ParserRule getRule() { return rule; }

		//"{" literals+=Literal ("," literals+=Literal)* "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//literals+=Literal
		public Assignment getLiteralsAssignment_1() { return cLiteralsAssignment_1; }

		//Literal
		public RuleCall getLiteralsLiteralParserRuleCall_1_0() { return cLiteralsLiteralParserRuleCall_1_0; }

		//("," literals+=Literal)*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//literals+=Literal
		public Assignment getLiteralsAssignment_2_1() { return cLiteralsAssignment_2_1; }

		//Literal
		public RuleCall getLiteralsLiteralParserRuleCall_2_1_0() { return cLiteralsLiteralParserRuleCall_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class StringLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringLiteral:
		//	value=STRING;
		public ParserRule getRule() { return rule; }

		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}

	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntLiteral:
		//	value=INT;
		public ParserRule getRule() { return rule; }

		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}

	public class FloatLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FloatLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueFLOATTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//FloatLiteral:
		//	value=FLOAT;
		public ParserRule getRule() { return rule; }

		//value=FLOAT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//FLOAT
		public RuleCall getValueFLOATTerminalRuleCall_0() { return cValueFLOATTerminalRuleCall_0; }
	}

	public class BooleanLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBOOLEANTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//BooleanLiteral:
		//	value=BOOLEAN;
		public ParserRule getRule() { return rule; }

		//value=BOOLEAN
		public Assignment getValueAssignment() { return cValueAssignment; }

		//BOOLEAN
		public RuleCall getValueBOOLEANTerminalRuleCall_0() { return cValueBOOLEANTerminalRuleCall_0; }
	}

	public class ConstantLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConstantLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cValueConstantCrossReference_0 = (CrossReference)cValueAssignment.eContents().get(0);
		private final RuleCall cValueConstantIDTerminalRuleCall_0_1 = (RuleCall)cValueConstantCrossReference_0.eContents().get(1);
		
		//ConstantLiteral:
		//	value=[Constant];
		public ParserRule getRule() { return rule; }

		//value=[Constant]
		public Assignment getValueAssignment() { return cValueAssignment; }

		//[Constant]
		public CrossReference getValueConstantCrossReference_0() { return cValueConstantCrossReference_0; }

		//ID
		public RuleCall getValueConstantIDTerminalRuleCall_0_1() { return cValueConstantIDTerminalRuleCall_0_1; }
	}

	public class BuiltInValueLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BuiltInValueLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBuiltInValueLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValueKIEKER_VERSIONKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//BuiltInValueLiteral:
		//	{BuiltInValueLiteral} value="KIEKER_VERSION";
		public ParserRule getRule() { return rule; }

		//{BuiltInValueLiteral} value="KIEKER_VERSION"
		public Group getGroup() { return cGroup; }

		//{BuiltInValueLiteral}
		public Action getBuiltInValueLiteralAction_0() { return cBuiltInValueLiteralAction_0; }

		//value="KIEKER_VERSION"
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//"KIEKER_VERSION"
		public Keyword getValueKIEKER_VERSIONKeyword_1_0() { return cValueKIEKER_VERSIONKeyword_1_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//(=> "." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//=> "."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName ("." "*")?;
		public ParserRule getRule() { return rule; }

		//QualifiedName ("." "*")?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//("." "*")?
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//"*"
		public Keyword getAsteriskKeyword_1_1() { return cAsteriskKeyword_1_1; }
	}
	
	
	public class PropertyModifierElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "PropertyModifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTRANSIENTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTRANSIENTTransientKeyword_0_0 = (Keyword)cTRANSIENTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINCREMENTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINCREMENTAutoIncrementKeyword_1_0 = (Keyword)cINCREMENTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum PropertyModifier:
		//	TRANSIENT="transient" | INCREMENT="auto-increment";
		public EnumRule getRule() { return rule; }

		//TRANSIENT="transient" | INCREMENT="auto-increment"
		public Alternatives getAlternatives() { return cAlternatives; }

		//TRANSIENT="transient"
		public EnumLiteralDeclaration getTRANSIENTEnumLiteralDeclaration_0() { return cTRANSIENTEnumLiteralDeclaration_0; }

		//"transient"
		public Keyword getTRANSIENTTransientKeyword_0_0() { return cTRANSIENTTransientKeyword_0_0; }

		//INCREMENT="auto-increment"
		public EnumLiteralDeclaration getINCREMENTEnumLiteralDeclaration_1() { return cINCREMENTEnumLiteralDeclaration_1; }

		//"auto-increment"
		public Keyword getINCREMENTAutoIncrementKeyword_1_0() { return cINCREMENTAutoIncrementKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final ImportElements pImport;
	private final PackageElements pPackage;
	private final TypeElements pType;
	private final TemplateTypeElements pTemplateType;
	private final RecordTypeElements pRecordType;
	private final ConstantElements pConstant;
	private final PropertyElements pProperty;
	private final ForeignKeyElements pForeignKey;
	private final PropertyModifierElements unknownRulePropertyModifier;
	private final ClassifierElements pClassifier;
	private final ArraySizeElements pArraySize;
	private final ReferencePropertyElements pReferenceProperty;
	private final LiteralElements pLiteral;
	private final ArrayLiteralElements pArrayLiteral;
	private final StringLiteralElements pStringLiteral;
	private final IntLiteralElements pIntLiteral;
	private final FloatLiteralElements pFloatLiteral;
	private final BooleanLiteralElements pBooleanLiteral;
	private final ConstantLiteralElements pConstantLiteral;
	private final BuiltInValueLiteralElements pBuiltInValueLiteral;
	private final QualifiedNameElements pQualifiedName;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final TerminalRule tNUMBER;
	private final TerminalRule tINT;
	private final TerminalRule tFLOAT;
	private final TerminalRule tBOOLEAN;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RecordLangGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pImport = new ImportElements();
		this.pPackage = new PackageElements();
		this.pType = new TypeElements();
		this.pTemplateType = new TemplateTypeElements();
		this.pRecordType = new RecordTypeElements();
		this.pConstant = new ConstantElements();
		this.pProperty = new PropertyElements();
		this.pForeignKey = new ForeignKeyElements();
		this.unknownRulePropertyModifier = new PropertyModifierElements();
		this.pClassifier = new ClassifierElements();
		this.pArraySize = new ArraySizeElements();
		this.pReferenceProperty = new ReferencePropertyElements();
		this.pLiteral = new LiteralElements();
		this.pArrayLiteral = new ArrayLiteralElements();
		this.pStringLiteral = new StringLiteralElements();
		this.pIntLiteral = new IntLiteralElements();
		this.pFloatLiteral = new FloatLiteralElements();
		this.pBooleanLiteral = new BooleanLiteralElements();
		this.pConstantLiteral = new ConstantLiteralElements();
		this.pBuiltInValueLiteral = new BuiltInValueLiteralElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NUMBER");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INT");
		this.tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FLOAT");
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BOOLEAN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.cau.cs.se.instrumentation.rl.RecordLang".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	"package" name=QualifiedName packages+=Package* imports+=Import* types+=Type*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Import:
	//	"import" importedNamespace=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Package:
	//	"use" name=ID package=[ecore::EPackage|STRING];
	public PackageElements getPackageAccess() {
		return pPackage;
	}
	
	public ParserRule getPackageRule() {
		return getPackageAccess().getRule();
	}

	//Type:
	//	RecordType | TemplateType;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//TemplateType:
	//	("@author" author=STRING)? ("@since" since=STRING)? "template" name=ID (":" parents+=[TemplateType|QualifiedName] (","
	//	parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?;
	public TemplateTypeElements getTemplateTypeAccess() {
		return pTemplateType;
	}
	
	public ParserRule getTemplateTypeRule() {
		return getTemplateTypeAccess().getRule();
	}

	//RecordType:
	//	("@author" author=STRING)? ("@since" since=STRING)? abstract?="abstract"? "entity" name=ID ("extends"
	//	parent=[RecordType|QualifiedName])? (":" parents+=[TemplateType|QualifiedName] (","
	//	parents+=[TemplateType|QualifiedName])*)? ("{" (properties+=Property | constants+=Constant)* "}")?;
	public RecordTypeElements getRecordTypeAccess() {
		return pRecordType;
	}
	
	public ParserRule getRecordTypeRule() {
		return getRecordTypeAccess().getRule();
	}

	//Constant:
	//	"const" type=Classifier name=ID "=" value=Literal;
	public ConstantElements getConstantAccess() {
		return pConstant;
	}
	
	public ParserRule getConstantRule() {
		return getConstantAccess().getRule();
	}

	//Property:
	//	modifiers+=PropertyModifier* foreignKey=ForeignKey? (type=Classifier | "alias" referTo=[Property] "as") name=ID ("{"
	//	properties+=ReferenceProperty* "}" | "=" value=Literal)?;
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//ForeignKey:
	//	"grouped" "by" recordType=[RecordType] "." propertyRef=[Property];
	public ForeignKeyElements getForeignKeyAccess() {
		return pForeignKey;
	}
	
	public ParserRule getForeignKeyRule() {
		return getForeignKeyAccess().getRule();
	}

	//enum PropertyModifier:
	//	TRANSIENT="transient" | INCREMENT="auto-increment";
	public PropertyModifierElements getPropertyModifierAccess() {
		return unknownRulePropertyModifier;
	}
	
	public EnumRule getPropertyModifierRule() {
		return getPropertyModifierAccess().getRule();
	}

	//Classifier:
	//	(package=[Package] ".")? class=[ecore::EClassifier] sizes+=ArraySize*;
	public ClassifierElements getClassifierAccess() {
		return pClassifier;
	}
	
	public ParserRule getClassifierRule() {
		return getClassifierAccess().getRule();
	}

	//ArraySize:
	//	{ArraySize} "[" size=INT? "]";
	public ArraySizeElements getArraySizeAccess() {
		return pArraySize;
	}
	
	public ParserRule getArraySizeRule() {
		return getArraySizeAccess().getRule();
	}

	//ReferenceProperty:
	//	ref=[ecore::EStructuralFeature] "{" properties+=ReferenceProperty* "}";
	public ReferencePropertyElements getReferencePropertyAccess() {
		return pReferenceProperty;
	}
	
	public ParserRule getReferencePropertyRule() {
		return getReferencePropertyAccess().getRule();
	}

	//Literal:
	//	StringLiteral | IntLiteral | FloatLiteral | BooleanLiteral | ConstantLiteral | ArrayLiteral | BuiltInValueLiteral;
	public LiteralElements getLiteralAccess() {
		return pLiteral;
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//ArrayLiteral:
	//	"{" literals+=Literal ("," literals+=Literal)* "}";
	public ArrayLiteralElements getArrayLiteralAccess() {
		return pArrayLiteral;
	}
	
	public ParserRule getArrayLiteralRule() {
		return getArrayLiteralAccess().getRule();
	}

	//StringLiteral:
	//	value=STRING;
	public StringLiteralElements getStringLiteralAccess() {
		return pStringLiteral;
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}

	//IntLiteral:
	//	value=INT;
	public IntLiteralElements getIntLiteralAccess() {
		return pIntLiteral;
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}

	//FloatLiteral:
	//	value=FLOAT;
	public FloatLiteralElements getFloatLiteralAccess() {
		return pFloatLiteral;
	}
	
	public ParserRule getFloatLiteralRule() {
		return getFloatLiteralAccess().getRule();
	}

	//BooleanLiteral:
	//	value=BOOLEAN;
	public BooleanLiteralElements getBooleanLiteralAccess() {
		return pBooleanLiteral;
	}
	
	public ParserRule getBooleanLiteralRule() {
		return getBooleanLiteralAccess().getRule();
	}

	//ConstantLiteral:
	//	value=[Constant];
	public ConstantLiteralElements getConstantLiteralAccess() {
		return pConstantLiteral;
	}
	
	public ParserRule getConstantLiteralRule() {
		return getConstantLiteralAccess().getRule();
	}

	//BuiltInValueLiteral:
	//	{BuiltInValueLiteral} value="KIEKER_VERSION";
	public BuiltInValueLiteralElements getBuiltInValueLiteralAccess() {
		return pBuiltInValueLiteral;
	}
	
	public ParserRule getBuiltInValueLiteralRule() {
		return getBuiltInValueLiteralAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName ("." "*")?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//// terminals
	//terminal fragment NUMBER:
	//	"0".."9";
	public TerminalRule getNUMBERRule() {
		return tNUMBER;
	} 

	//// redefine INT terminal to allow negative numbers
	//terminal INT returns ecore::EInt:
	//	"-"? NUMBER+;
	public TerminalRule getINTRule() {
		return tINT;
	} 

	//// make sure the Float rule does not shadow the INT rule
	//terminal FLOAT returns ecore::EFloatObject:
	//	"-"? NUMBER+ ("." NUMBER*) (("e" | "E") ("+" | "-")? NUMBER+)? "f"? | "-"? NUMBER+ "f";
	public TerminalRule getFLOATRule() {
		return tFLOAT;
	} 

	//// introduce boolean values
	//terminal BOOLEAN returns ecore::EBooleanObject:
	//	"true" | "false";
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
