/*
 * generated by Xtext
 */
package de.cau.cs.se.instrumentation.rl.ui.contentassist

import de.cau.cs.se.instrumentation.rl.ui.contentassist.AbstractRecordLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class RecordLangProposalProvider extends AbstractRecordLangProposalProvider {
}
