/**
 * generated by Xtext
 */
package kieker.develop.al.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class AspectLangLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public AspectLangLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final /* Aspect */Object e) {
    return "aspect";
  }
  
  public CharSequence text(final /* ContainerNode */Object e) {
    throw new Error("Unresolved compilation problems:"
      + "\ncontainer cannot be resolved"
      + "\ncontainer cannot be resolved"
      + "\ncontainer cannot be resolved"
      + "\nclass cannot be resolved"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* WildcardNode */Object e) {
    return "*";
  }
  
  public String text(final /* SubPathNode */Object e) {
    return "**";
  }
  
  public String text(final /* Pointcut */Object e) {
    throw new Error("Unresolved compilation problems:"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* LocationQuery */Object e) {
    return "path";
  }
  
  public Object text(final /* Collector */Object e) {
    return null;
  }
}
