/*
 * generated by Xtext
 */
package de.cau.cs.se.instrumentation.rl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRecordLangValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.cau.cs.se.instrumentation.rl.recordLang.RecordLangPackage.eINSTANCE);
		return result;
	}
}
