/*
 * generated by Xtext 2.25.0
 */
package kieker.develop.al.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AspectLangUiModule extends AbstractAspectLangUiModule {

	public AspectLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
