/*
 * generated by Xtext 2.25.0
 */
package kieker.develop.al.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kieker.develop.al.AspectLangRuntimeModule;
import kieker.develop.al.AspectLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AspectLangIdeSetup extends AspectLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AspectLangRuntimeModule(), new AspectLangIdeModule()));
	}
	
}
