/**
 *
 * $Id$
 */
package kieker.develop.al.mapping.validation;

import kieker.develop.al.mapping.TypeReference;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link kieker.develop.al.mapping.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateType(TypeReference value);
	boolean validateValue(EObject value);
}
