/**
 *
 * $Id$
 */
package kieker.develop.al.mapping.validation;

import kieker.develop.al.mapping.Attribute;
import kieker.develop.al.mapping.ContainerModifier;
import kieker.develop.al.mapping.Operation;
import kieker.develop.al.mapping.Reference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kieker.develop.al.mapping.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateModifier(ContainerModifier value);
	boolean validateOperations(EList<Operation> value);
	boolean validateAttributes(EList<Attribute> value);
	boolean validateReferences(Reference value);
}
