/**
 *
 * $Id$
 */
package kieker.develop.al.mapping.validation;

import kieker.develop.al.mapping.Container;
import kieker.develop.al.mapping.NamedType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kieker.develop.al.mapping.Containment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainmentValidator {
	boolean validate();

	boolean validateContents(EList<Container> value);
	boolean validateTypes(EList<NamedType> value);
}
