/*
 * generated by Xtext
 */
package de.cau.se.instrumentation.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProbeLangRuntimeModule extends de.cau.se.instrumentation.language.AbstractProbeLangRuntimeModule {

}
